# Generated by Django 6.0.4 on 2026-07-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderstatushistory_options_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
