# Generated by Django 6.0.4 on 2026-07-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_item_image_orderitem_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
    ]
