# Generated by Django 6.0.4 on 2026-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderitem_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
